# **Deep Natural Language Processing @ PoliTO**

---


**Teaching Assistant:** Giuseppe Gallipoli

**Credits:** Moreno La Quatra

**Practice 3:** Named Entity Recognition (part 1) & Intent Detection (part 2)

## Intent Detection

In data mining, intention mining or intent mining is the problem of determining a user's intention from logs of his/her behavior in interaction with a computer system, such as in search engines. Intent Detection is the identification and categorization of what a user online intended or wanted to find when they type or speak with a conversational agent (or a search engine).

![https://d33wubrfki0l68.cloudfront.net/32e2326762c75a0357ab1ae1976a60d4bbce724b/f4ac0/static/a5878ba6b0e4e77163dc07d07ecf2291/2b6c7/intent-classification-normal.png](https://d33wubrfki0l68.cloudfront.net/32e2326762c75a0357ab1ae1976a60d4bbce724b/f4ac0/static/a5878ba6b0e4e77163dc07d07ecf2291/2b6c7/intent-classification-normal.png)

In this section, you will use the ATIS dataset: https://github.com/yvchen/JointSLU; https://www.kaggle.com/siddhadev/atis-dataset-clean/home

The task is to classify the intent of a sentence. The dataset is split into train, validation and test sets. **Use the provided splits** to train and evaluate your models.

In [41]:
!wget https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.train.csv
!wget https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.dev.csv
!wget https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.test.csv

--2025-10-29 14:44:33--  https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 838864 (819K) [text/plain]
Saving to: ‘atis.train.csv.4’

atis.train.csv.4    100%[===================>] 819.20K  --.-KB/s    in 0.02s

2025-10-29 14:44:33 (45.8 MB/s) - ‘atis.train.csv.4’ saved [838864/838864]

--2025-10-29 14:44:34--  https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.dev.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 112033 (109K) [text/plain]
Saving to: ‘atis.dev.csv.4’

atis.dev.csv.4      100%[===================>] 109.41K  --.-KB/s    in 0.009s

2025-10-29 14:44:34 (12.3 MB/s) - ‘atis.dev.csv.4’ saved [112033/112033]

--2025-10-29 14:44:34--  https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P4/IntentDetection/atis.test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113557 (111K) [text/plain]
Saving to: ‘atis.test.csv.4’

atis.test.csv.4     100%[===================>] 110.90K  --.-KB/s    in 0.007s

2025-10-29 14:44:34 (15.6 MB/s) - ‘atis.test.csv.4’ saved [113557/113557]

### **Question 5: Two-step classification model**

Train a classification model to identify the intent from a given sentence. The model is required to leverage on pre-trained BERT model to generate sentence embeddings (important: **no fine-tuning**). The model is required to use the embeddings to perform classification.

Once extracted the embeddings, you can use any classifier you want. For example, you can use a linear classifier (e.g., Logistic Regression) or a neural network (e.g., MLP). For your convenience, you can use the `sklearn` library for training the classifier (https://scikit-learn.org/stable/supervised_learning.html).

![https://github.com/MorenoLaQuatra/DeepNLP/blob/main/practices/P4/IntentDetection/no_finetuning.png?raw=true](https://github.com/MorenoLaQuatra/DeepNLP/blob/main/practices/P4/IntentDetection/no_finetuning.png?raw=true)


Assess the performance of the trained model (the model on top of BERT) on the test set by using the **classification accuracy**, **precision**, **recall** and **F1-score**. You can use the `sklearn` library for computing the metrics (https://scikit-learn.org/stable/api/sklearn.metrics.html).


Note: you can use the `sentence-transformers` library to generate sentence embeddings (https://www.sbert.net/docs/pretrained_models.html).

In [ ]:
%%capture
!pip install sentence-transformers
!pip install sklearn

In [ ]:
# your code here
import pandas as pd

df_train = pd.read_csv('atis-train.csv')
df_val = pd.read_csv('atis-dev.csv')
df_test = pd.read_csv('atis-test.csv')

labels = {}
for i, cls in enumerate(df_train['intent'].unique()):
  labels[cls] = i

df_train['intent'] = df_train['intent'].apply(lambda x: labels[x])
df_val['intent'] = df_val['intent'].apply(lambda x: labels[x])
df_test['intent'] = df_test['intent'].apply(lambda x: labels[x])

In [ ]:
df_train.head(5)

,id,tokens,slots,intent
0,train-00001,BOS what is the cost of a round trip flight fr...,O O O O O O O B-round_trip I-round_trip O O B-...,0
1,train-00002,BOS now i need a flight leaving fort worth and...,O O O O O O O B-fromloc.city_name I-fromloc.ci...,1
2,train-00003,BOS i need to fly from kansas city to chicago ...,O O O O O O B-fromloc.city_name I-fromloc.city...,1
3,train-00004,BOS what is the meaning of meal code s EOS,O O O O O O B-meal_code I-meal_code I-meal_code O,2
4,train-00005,BOS show me all flights from denver to pittsbu...,O O O O O O B-fromloc.city_name O B-toloc.city...,1

In [ ]:
df_val.head(5)

,id,tokens,slots,intent
0,dev-00001,BOS i would like the cheapest flight from pitt...,O O O O O B-cost_relative O O B-fromloc.city_n...,1
1,dev-00002,BOS i want a flight from memphis to seattle th...,O O O O O O B-fromloc.city_name O B-toloc.city...,1
2,dev-00003,BOS show me round trip flights from chicago to...,O O O B-round_trip I-round_trip O O B-fromloc....,1
3,dev-00004,BOS what does d s stand for for meals EOS,O O O B-meal_code I-meal_code O O O B-meal O,2
4,dev-00005,BOS show me all flights from atlanta to denver...,O O O O O O B-fromloc.city_name O B-toloc.city...,1

In [ ]:
df_test.head(5)

,id,tokens,slots,intent
0,test-00001,BOS what are the coach flights between dallas ...,O O O O B-class_type O O B-fromloc.city_name O...,1
1,test-00002,BOS i want a flight from nashville to seattle ...,O O O O O O B-fromloc.city_name O B-toloc.city...,1
2,test-00003,BOS i need a flight leaving kansas city to chi...,O O O O O O B-fromloc.city_name I-fromloc.city...,1
3,test-00004,BOS explain meal codes sd d EOS,O O B-meal O B-meal_code I-meal_code O,2
4,test-00005,BOS show me all flights from atlanta to san fr...,O O O O O O B-fromloc.city_name O B-toloc.city...,1

In [ ]:
import torch
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [ ]:
list_train = df_train['tokens'].to_list()
list_val = df_val['tokens'].to_list()
list_test = df_test['tokens'].to_list()

In [ ]:
X_train = model.encode(list_train)
y_train = df_train['intent'].to_numpy()

X_val = model.encode(list_val)
y_val = df_val['intent'].to_numpy()

X_test = model.encode(list_test)
y_test = df_test['intent'].to_numpy()

In [ ]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = lr_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Accuracy: 0.9112627986348123
Precision: 0.5490625472755322
Recall: 0.4111940507425409
F1-score: 0.44840079804496247

### **Question 6: Fine-tuning end-to-end classification model**

Another approach is to fine-tune the BERT model for the classification task. A classification head is added on top of the pre-trained BERT model. The classification head is trained end-to-end with the BERT model.
This approach is more effective than the previous one because the model is trained end-to-end. However, the model requires more training time and resources.

Train a new BERT model for the task of [sequence classification](https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertForSequenceClassification) (include BERT fine-tuning).  

![https://github.com/MorenoLaQuatra/DeepNLP/blob/main/practices/P4/IntentDetection/finetuning.png?raw=true](https://github.com/MorenoLaQuatra/DeepNLP/blob/main/practices/P4/IntentDetection/finetuning.png?raw=true)

Assess the performance of the generated model by using the same metrics used in the previous question.

Which model has better performance? Why?

In [ ]:
# your code here
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(labels)).to('cuda')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
tokenized_train = tokenizer(list_train, padding=True, truncation=True, max_length=512, return_tensors='pt').to('cuda')
tokenized_val = tokenizer(list_val, padding=True, truncation=True, max_length=512, return_tensors='pt').to('cuda')
tokenized_test = tokenizer(list_test, padding=True, truncation=True, max_length=512, return_tensors='pt').to('cuda')

In [ ]:
tokenized_train

{'input_ids': tensor([[ 101, 8945, 2015,  ...,    0,    0,    0],
        [ 101, 8945, 2015,  ...,    0,    0,    0],
        [ 101, 8945, 2015,  ...,    0,    0,    0],
        ...,
        [ 101, 8945, 2015,  ...,    0,    0,    0],
        [ 101, 8945, 2015,  ...,    0,    0,    0],
        [ 101, 8945, 2015,  ...,    0,    0,    0]], device='cuda:0'), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0')}

In [ ]:
class Dataset(torch.utils.data.Dataset):
  def __init__(self, encodings, labels):
    self.encodings = encodings
    self.labels = labels

  def __getitem__(self, idx):
    item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}
    item['labels'] = torch.tensor(self.labels[idx]).cpu()
    return item

  def __len__(self):
    return len(self.labels)

In [ ]:
dataset_train = Dataset(tokenized_train, y_train)
dataset_val = Dataset(tokenized_val, y_val)
dataset_test = Dataset(tokenized_test, y_test)

In [ ]:
training_arguments = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=5,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=64,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    eval_strategy="epoch"
)

In [ ]:
# Move computation to GPU
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=17, bias=True)
)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_arguments,
    train_dataset=dataset_train,
    eval_dataset=dataset_val
)

trainer.train()

/tmp/ipython-input-1321093805.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}

/tmp/ipython-input-1321093805.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}
/tmp/ipython-input-1321093805.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}
/tmp/ipython-input-1321093805.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}

TrainOutput(global_step=1340, training_loss=0.29395839570701787, metrics={'train_runtime': 306.019, 'train_samples_per_second': 69.832, 'train_steps_per_second': 4.379, 'total_flos': 615063805792800.0, 'train_loss': 0.29395839570701787, 'epoch': 5.0})

In [ ]:
predictions = trainer.predict(dataset_test)
y_pred = predictions.predictions.argmax(axis=1)

/tmp/ipython-input-1321093805.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]).cpu() for key, val in self.encodings.items()}

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1: {f1}")

Accuracy: 0.9880546075085325
Precision: 0.906829717702684
Recall: 0.9090725913006713
F1: 0.9040162307436441

### **Question 7: Intent Detection using Large Language Models**
**Credits:** Giuseppe Gallipoli

#### Introduction
[Large Language Models](https://en.wikipedia.org/wiki/Large_language_model) (LLMs) are a type of deep learning model capable of language generation. These models are built on deep learning architectures, primarily using neural networks, and are trained on massive amounts of text data. LLMs generally leverage the *Transformer* architecture, which allows them to process language in context, capturing complex relationships between words and concepts.

Large Language Models have demonstrated excellent capabilities across a wide variety of tasks, making them versatile models which can be applied in diverse scenarios and use cases. Although they are more typically used for *generative* tasks (e.g., text generation, text summarization, open-ended Question Answering), they can also be employed in *discriminative* tasks.

In this practice, we will use a Large Language Model to address an intent detection task. Rather than using a pre-trained encoder-only model without (Question 5) or with fine-tuning (Question 6), we will ask the LLM to classify the intent given a sentence of interest.
<br><br>
For now, we will use the [Phi-4-mini-instruct](https://huggingface.co/microsoft/Phi-4-mini-instruct) 3.8B model, i.e., `microsoft/Phi-4-mini-instruct`.

#### LLM Prompting
To interact with LLMs, we need to define a **prompt**, which is a piece of text containing the instruction or question we want to give or ask the model. As we saw in Practice 1 (Exercise 11), a prompt can both include only the instruction/question for the LLM but also additional information (i.e., *context*) which can be exploited by the model to generate the answer.

For now, we will ask the model to classify the intent of a given sentence <u>without providing</u> any additional context. Please note that, since we want to (potentially) limit the choice of the LLM to a predefined list of intents (i.e., the set of labels of our dataset), we will also provide this list to the model.\
*Example of prompt*:\
Which is the intent of the following sentence?\
Choose among: label1, label2, ...
<br><br>

**Hint**: For those data instances whose intent is the concatenation of two intents (i.e., `atis_flight#atis_airfare`), consider only the first one.

<u>Suggestion</u>: To increase speed, switch to a GPU runtime. You can do this by clicking on Runtime → Change runtime type → Hardware accelerator → Select T4 GPU.\
If you encounter an `OutOfMemoryError`, try restarting the session by clicking on Runtime → Restart session.

In [42]:
!pip install -U bitsandbytes

Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.48.1)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)

In [43]:
# your code here
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import bitsandbytes

In [44]:
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-4-mini-instruct",
    load_in_4bit=True,
    dtype=torch.float16
).to('cuda')
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-4-mini-instruct", padding_side='left')

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [45]:
import pandas as pd

In [46]:
df_train = pd.read_csv('atis-train.csv')
df_val = pd.read_csv('atis-dev.csv')
df_test = pd.read_csv('atis-test.csv')

In [47]:
labels = df_train['intent'].unique()
labels_set = set()
for l in labels:
  if '#' in l:
    l = l.split('#')[0]
  labels_set.add(l)
labels = list(labels_set)
print(labels)

['atis_flight', 'atis_airline', 'atis_flight_time', 'atis_flight_no', 'atis_distance', 'atis_airfare', 'atis_abbreviation', 'atis_restriction', 'atis_aircraft', 'atis_ground_service', 'atis_ground_fare', 'atis_quantity', 'atis_capacity', 'atis_airport', 'atis_city', 'atis_meal']

In [48]:
labels_string = ', '.join(labels)
print(labels_string)

atis_flight, atis_airline, atis_flight_time, atis_flight_no, atis_distance, atis_airfare, atis_abbreviation, atis_restriction, atis_aircraft, atis_ground_service, atis_ground_fare, atis_quantity, atis_capacity, atis_airport, atis_city, atis_meal

In [49]:
sentence = df_test['tokens'].iloc[0]
prompt_template = (
    f"Which is the intent of the following sentence?\n"
    f"Choose among: {labels_string}\n\n"
    f"Sentence: {sentence}\n"
    f"Intent:"
)
print(prompt_template)

Which is the intent of the following sentence?
Choose among: atis_flight, atis_airline, atis_flight_time, atis_flight_no, atis_distance, atis_airfare, atis_abbreviation, atis_restriction, atis_aircraft, atis_ground_service, atis_ground_fare, atis_quantity, atis_capacity, atis_airport, atis_city, atis_meal

Sentence: BOS what are the coach flights between dallas and baltimore leaving august tenth and returning august twelve EOS
Intent:

In [50]:
tokenized = tokenizer(prompt_template, return_tensors='pt').to('cuda')
output = model.generate(**tokenized, max_new_tokens=100, pad_token_id=tokenizer.eos_token_id)

input_length = tokenized['input_ids'].shape[1]

print(tokenizer.decode(output[0, input_length:], skip_special_tokens=True))

 atis_flight_time

In [51]:
from tqdm import tqdm

In [ ]:
prompt_template = (
    f"Which is the intent of the following sentence? JUST GIVE THE EXACT LABEL\n"
    f"Choose among: {labels_string}\n\n"
    f"Sentence: {{sentence}}\n"
    f"Intent:"
)
prompt_list = [prompt_template.format(sentence=prompt) for prompt in df_test['tokens']]

batch_size = 16
decoded_list = []

for i in tqdm(range(0, len(prompt_list), batch_size)):
    batch_prompts = prompt_list[i : i + batch_size]

    tokenized_batch = tokenizer(
        batch_prompts,
        return_tensors='pt',
        padding=True,
        truncation=True,
        max_length=512
    ).to(model.device)

    input_length = tokenized_batch['input_ids'].shape[1]

    with torch.no_grad():
        output_ids = model.generate(
            **tokenized_batch,
            max_new_tokens=20,
            pad_token_id=tokenizer.eos_token_id
        )

    new_tokens = output_ids[:, input_length:]
    decoded_batch = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)

    decoded_list.extend(decoded_batch)

print("Generation complete.")
print(f"Total predictions generated: {len(decoded_list)}")

100%|██████████| 37/37 [04:58<00:00,  8.08s/it]

Generation complete.
Total predictions generated: 586

#### Few-Shot Learning
When we provide the LLM with additional context to be leveraged for generating an answer, this is known as *in-context learning* (ICL).\
A common technique to perform ICL involves including one or more **additional examples** of questions (or instructions) and their expected answers in the prompt.\
This can be useful for several reasons: telling the model the required output format, both in terms of structure and style, making the model reason about the provided examples to better adapt to the (new) task, tailoring model's responses to a user's specific needs, ...\
All of this is done directly at inference, without the need of further training the model, simply by leveraging the reasoning and generalization capabilities of LLMs.\
When no examples are provided, as in the previous point of the exercise, we talk about **zero-shot** learning. Conversely, when we supply additional input-output examples in the model's prompt, we talk about **few-shot** learning or $k$-shot learning, where $k$ represents the number of ICL examples.\
Examples can be selected according to different strategies, either randomly or in a more clever way, but please note that they <u>must be chosen from the training set</u> to avoid *data leakage*.
<br><br>

Now, try to implement few-shot learning by modifying the previous point of the exercise so that the prompt can include $k$ additional examples.

In [64]:
# your code here
example_rows = df_train.sample(n=3, random_state=45)
print(example_rows)

               id                                             tokens  \
794   train-00795  BOS show me the least expensive flight leaving...
4222  train-04223  BOS show me flights leaving from dallas to bal...
1646  train-01647                          BOS define airline hp EOS

                                                  slots        intent
794   O O O O B-cost_relative I-cost_relative O O B-...   atis_flight
4222  O O O O O O B-fromloc.city_name O B-toloc.city...   atis_flight
1646                             O O O B-airline_code O  atis_airline

In [65]:
examples = []
for i, row in example_rows.iterrows():
  sentence = row['tokens']
  intent = row['intent']
  example_string = f"Sentence: {sentence}\nIntent: {intent}"
  examples.append(example_string)
example_string = '\n\n'.join(examples)
print(example_string)

Sentence: BOS show me the least expensive flight leaving miami on sunday after 12 o'clock noon and arriving cleveland EOS
Intent: atis_flight

Sentence: BOS show me flights leaving from dallas to baltimore EOS
Intent: atis_flight

Sentence: BOS define airline hp EOS
Intent: atis_airline

In [66]:
task_description = (
    "Your task is to classify the intent of a given sentence. "
    "You must choose one intent from the 'Allowed Intents' list. "
    "Respond with only the exact intent label and nothing else."
)

examples = f"EXAMPLES:\n\n{example_string}"

allowed_intents = f"ALLOWED INTENTS:\n{labels_string}"

query = "Sentence: {{sentence}}\nIntent:"

prompt_template = (
    f"{task_description}\n\n"
    f"{allowed_intents}\n\n"
    f"{examples}\n\n"
    f"---"  # A separator
    f"Now, complete the following task:\n\n"
    f"{query}"
)

print(prompt_template.format(sentence="this is a test sentence"))

Your task is to classify the intent of a given sentence. You must choose one intent from the 'Allowed Intents' list. Respond with only the exact intent label and nothing else.

ALLOWED INTENTS:
atis_flight, atis_airline, atis_flight_time, atis_flight_no, atis_distance, atis_airfare, atis_abbreviation, atis_restriction, atis_aircraft, atis_ground_service, atis_ground_fare, atis_quantity, atis_capacity, atis_airport, atis_city, atis_meal

EXAMPLES:

Sentence: BOS show me the least expensive flight leaving miami on sunday after 12 o'clock noon and arriving cleveland EOS
Intent: atis_flight

Sentence: BOS show me flights leaving from dallas to baltimore EOS
Intent: atis_flight

Sentence: BOS define airline hp EOS
Intent: atis_airline

---Now, complete the following task:

Sentence: {sentence}
Intent:

Try with different $k$ values, e.g., $k \in [1, 3, 5, 10]$, and see if and how the model's performance changes.

In [71]:
# your code here
prompt_list = [prompt_template.format(sentence=prompt) for prompt in df_test['tokens']]

batch_size = 16
decoded_list = []

for i in tqdm(range(0, batch_size*1, batch_size)):
    batch_prompts = prompt_list[i : i + batch_size]

    tokenized_batch = tokenizer(
        batch_prompts,
        return_tensors='pt',
        padding=True,
        truncation=True,
        max_length=512
    ).to(model.device)

    input_length = tokenized_batch['input_ids'].shape[1]

    with torch.no_grad():
        output_ids = model.generate(
            **tokenized_batch,
            max_new_tokens=20,
            pad_token_id=tokenizer.eos_token_id
        )

    new_tokens = output_ids[:, input_length:]
    decoded_batch = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)

    decoded_list.extend(decoded_batch)

print("Generation complete.")
print(f"Total predictions generated: {len(decoded_list)}")

100%|██████████| 1/1 [00:07<00:00,  7.99s/it]

Generation complete.
Total predictions generated: 16

In [72]:
for d in decoded_list:
  print(d)

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

 atis_flight_time

Until now, we have used the [Phi-4-mini-instruct](https://huggingface.co/microsoft/Phi-4-mini-instruct) 3.8B model, i.e., `microsoft/Phi-4-mini-instruct`, but there are plenty of LLMs!\
Try another model of your choice, e.g., [Mistral-Instruct](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3) 7B `mistralai/Mistral-7B-Instruct-v0.3`. Remember to always keep in mind the GPU memory constraints you have.
<br><br>

**Hint**: To download and use certain models, it may be needed to request access to them (e.g., [Llama3.2-Instruct](https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct) 3B). This can be done from the Hugging Face model page after logging in. Once access is granted, you need to create your personal access token (go to your HF profile, Settings → Access Tokens → Create new token) and authenticate using it when downloading both the model and the tokenizer.\
To authenticate, you can either use the additional `token` parameter in the `from_pretrained()` method or via the [HF Command Line Interface](https://huggingface.co/docs/huggingface_hub/guides/cli).
```
model_tag = 'MODEL_TAG'
HF_TOKEN = 'MY_HF_TOKEN'

model = AutoModelForCausalLM.from_pretrained(model_tag, torch_dtype=torch.float16, token=HF_TOKEN, device_map=device)
tokenizer = AutoTokenizer.from_pretrained(model_tag, token=HF_TOKEN)
```

In [ ]:
# your code here

After analyzing the performance of the different settings and/or models, here you can find some questions to reason about the results:
- What is the performance in the zero-shot learning setting? (i.e., $k=0$)
- How does it change when providing one additional example? (i.e., $k=1$)
- What happens when increasing the number of ICL examples?
- If you tested additional models, which one performs best in the zero-shot and few-shot learning settings?
- What challenges or limitations did you observe?